import React from 'react';
import Head from 'next/head';
import NavBar from '../components/NavBar';

const contact = () => {
    return (
        <>
            <Head>
                <title>Landing Page - Contatos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />

            <div>Contact</div>
        </>
    );
};

export default contact;