import React from 'react';
import Head from 'next/head';
import NavBar from '../components/NavBar';
import Footer from '../components/Footer';

const stock = () => {
    return (
        <>
            <Head>
                <title>Landing Page - Estoque</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />

            <section className='flex flex-wrap items-center justify-center h-[70rem] bg-secondarybg text-white'>
          <h1 className='text-center w-full h-[1rem] mt-auto font-bold text-2xl mb-2'>Compre agora</h1>

          <div className='flex flex-wrap items-center justify-center  mx-2 xl:mx-48 2xl:mx-80'>
            <div className='h-[8rem] md:h-[14rem] lg:h-[16rem] m-1 bg-white/10 shadow-2xl blur-[1px] hover:blur-0 overflow-hidden'>
              <img src='/carimg1.jpg' alt='car image'
              className='h-full hover:scale-125 transition duration-500 ease-in-out'></img>
            </div>

            <div className='h-[8rem] md:h-[14rem] lg:h-[16rem] m-1 bg-white/10 shadow-2xl blur-[1px] hover:blur-0 overflow-hidden'>
              <img src='/carimg2.jpg' alt='car image'
              className='h-full hover:scale-125 transition duration-500 ease-in-out'></img>
            </div>

            <div className='h-[8rem] md:h-[14rem] lg:h-[16rem] m-1 bg-white/10 shadow-2xl blur-[1px] hover:blur-0 overflow-hidden'>
              <img src='/carimg3.jpg' alt='car image'
              className='h-full hover:scale-125 transition duration-500 ease-in-out'></img>
            </div>

            <div className='h-[8rem] md:h-[14rem] lg:h-[16rem] m-1 bg-white/10 shadow-2xl blur-[1px] hover:blur-0 overflow-hidden'>
              <img src='/carimg4.jpg' alt='car image'
              className='h-full hover:scale-125 transition duration-500 ease-in-out'></img>
            </div>

            <div className='h-[8rem] md:h-[14rem] lg:h-[16rem] m-1 bg-white/10 shadow-2xl blur-[1px] hover:blur-0 overflow-hidden'>
              <img src='/carimg5.jpg' alt='car image'
              className='h-full hover:scale-125 transition duration-500 ease-in-out'></img>
            </div>

            <div className='h-[8rem] md:h-[14rem] lg:h-[16rem] m-1 bg-white/10 shadow-2xl blur-[1px] hover:blur-0 overflow-hidden'>
              <img src='/carimg6.jpg' alt='car image'
              className='h-full hover:scale-125 transition duration-500 ease-in-out'></img>
            </div>

            <div className='h-[8rem] md:h-[14rem] lg:h-[16rem] m-1 bg-white/10 shadow-2xl blur-[1px] hover:blur-0 overflow-hidden'>
              <img src='/carimg7.jpg' alt='car image'
              className='h-full hover:scale-125 transition duration-500 ease-in-out'></img>
            </div>

            <div className='h-[8rem] md:h-[14rem] lg:h-[16rem] m-1 bg-white/10 shadow-2xl blur-[1px] hover:blur-0 overflow-hidden'>
              <img src='/carimg1.jpg' alt='car image'
              className='h-full hover:scale-125 transition duration-500 ease-in-out'></img>
            </div>

          </div>

        </section>

        <Footer />
        </>
    );
};

export default stock;